CONFIG = ['INCLUDE_PATH', 'MCU', 'F_CPU', 'EXTRA_LIBS', 'AVR_GCC_DIR', 'TARGET', 'LIBS', 'LIBPATH', 'SOURCEPATH', 'QUALIA_DIR', 'platform', 'mode']

Import(CONFIG)

if (platform == 'computer'):
  INCLUDE_PATH = "/Users/tats/Documents/workspace/qualia"
else:
  INCLUDE_PATH = "/Users/tats/Documents/workspace/qualia/src:/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/avr/include/"

QUALIA_DIR = "../.."

MCU = 'atmega328p'
F_CPU = 16000000
EXTRA_LIBS = ""

if (platform == 'avr'):
  AVR_GCC_DIR = "/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/"

if (platform == 'arduino'):
  TARGET = 'MainTest'
else:
  TARGET = "small"

Return(CONFIG)
