CONFIG = ['INCLUDE_PATH', 'MCU', 'F_CPU', 'EXTRA_LIBS', 'AVR_GCC_DIR', 'TARGET', 'LIBS', 'LIBPATH', 'SOURCEPATH', 'QUALIA_DIR', 'platform', 'mode']

Import(CONFIG)

QUALIA_DIR = "../../"
QUALIA_BUILD_DIR = QUALIA_DIR + "/build/" + platform

INCLUDE_PATH = QUALIA_BUILD_DIR + ":" + "/usr/local/include/mapper-0"
LIBPATH      = QUALIA_BUILD_DIR + ":" + "/usr/local/lib"

LIBS = "qualia,m,mapper-0,lo"

if (platform != 'computer'):
  raise RuntimeError("Arduino mode not supported for this program")
else:
  TARGET = "main"

Return(CONFIG)
