CONFIG = ['INCLUDE_PATH', 'MCU', 'F_CPU', 'EXTRA_LIBS', 'AVR_GCC_DIR', 'TARGET', 'LIBS', 'LIBPATH', 'SOURCEPATH', 'QUALIA_DIR', 'platform', 'mode']

Import(CONFIG)

QUALIA_DIR = "../../"
QUALIA_BUILD_DIR = QUALIA_DIR + "/build/" + platform

INCLUDE_PATH = QUALIA_BUILD_DIR
LIBPATH      = QUALIA_BUILD_DIR

LIBS = 'qualia,m,lo'


if (platform != 'computer'):
  raise RuntimeError("Arduino mode not supported for this program")
else:
  TARGET = "osc_bt"

Return(CONFIG)
