CONFIG = ['INCLUDE_PATH', 'MCU', 'F_CPU', 'EXTRA_LIBS', 'AVR_GCC_DIR', 'TARGET', 'LIBS', 'LIBPATH', 'SOURCEPATH', 'QUALIA_DIR', 'platform', 'mode']

Import(CONFIG)

QUALIA_DIR = "../../"
QUALIA_BUILD_DIR = QUALIA_DIR + "/build/" + platform

INCLUDE_PATH = QUALIA_BUILD_DIR
LIBPATH      = QUALIA_BUILD_DIR

#if (platform == 'computer'):
#  INCLUDE_PATH = "/Users/tats/Documents/workspace/qualia"
#else:
#  INCLUDE_PATH = "/Users/tats/Documents/workspace/qualia/src:/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/avr/include/"

#QUALIA_DIR = "/Users/tats/Documents/workspace/qualia"
LIBS = 'qualia,m,lo'

MCU = 'atmega328p'
F_CPU = 16000000
EXTRA_LIBS = ""

if (platform == 'arduino'):
  raise RuntimeError("Arduino mode not supported for this program")
  TARGET = 'MainTest'
else:
  TARGET = "main"

Return(CONFIG)
