CONFIG = ['INCLUDE_PATH', 'MCU', 'F_CPU', 'EXTRA_LIBS', 'AVR_GCC_DIR', 'TARGET', 'LIBS', 'LIBPATH', 'SOURCEPATH', 'QUALIA_DIR', 'platform', 'mode']

Import(CONFIG)

INCLUDE_PATH = "../../src:/usr/local/include/mapper-0"

if (platform == 'computer'):
  LIBS = "libmapper-0,liblo"

TARGET = "main_test"

Return(CONFIG)
