CONFIG = ['INCLUDE_PATH', 'MCU', 'F_CPU', 'EXTRA_LIBS', 'AVR_GCC_DIR', 'TARGET', 'LIBS', 'LIBPATH', 'platform', 'mode']

Import(CONFIG)

if (platform == 'computer'):
  INCLUDE_PATH = "/Users/tats/Documents/workspace/qualia/src:/Users/tats/Documents/workspace/emerge/emerge-local/devel/libmapper/include"
  LIBS = "libmapper-0,liblo"
else:
  INCLUDE_PATH = "/Users/tats/Documents/workspace/qualia/src:/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/avr/include/"

MCU = 'atmega168'
F_CPU = 16000000
EXTRA_LIBS = ""

if (platform == 'avr'):
  AVR_GCC_DIR = "/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/"

if (platform == 'arduino'):
  TARGET = 'SimpleFirmware'
else:
  TARGET = "main_test"

Return(CONFIG)
