CONFIG = ['INCLUDE_PATH', 'MCU', 'F_CPU', 'EXTRA_LIBS', 'AVR_GCC_DIR', 'MODE', 'TARGET']

Import(CONFIG)

INCLUDE_PATH = "/Users/tats/Documents/workspace/qualia:/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/avr/include/"
MCU = 'atmega168'
F_CPU = 16000000
EXTRA_LIBS = ""

AVR_GCC_DIR = "/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/"

#MODE = 'arduino'
#TARGET = "MainTest"

Return(CONFIG)