CONFIG = ['INCLUDE_PATH', 'MCU', 'F_CPU', 'EXTRA_LIBS', 'AVR_GCC_DIR', 'TARGET', 'LIBS', 'LIBPATH', 'SOURCEPATH', 'QUALIA_DIR', 'platform', 'mode']

Import(CONFIG)

QUALIA_DIR = "../../"
QUALIA_BUILD_DIR = QUALIA_DIR + "/build/" + platform

INCLUDE_PATH = QUALIA_BUILD_DIR
LIBPATH      = QUALIA_BUILD_DIR

MCU = 'atmega168'
F_CPU = 16000000
EXTRA_LIBS = ""

if (platform == 'arduino'):
  raise RuntimeError("Arduino mode not supported for this program")
  TARGET = 'MainTest'
else:
  TARGET = "unit_test"

Return(CONFIG)