CONFIG = ['INCLUDE_PATH', 'MCU', 'F_CPU', 'EXTRA_LIBS', 'AVR_GCC_DIR', 'TARGET', 'LIBS', 'LIBPATH', 'SOURCEPATH', 'QUALIA_DIR', 'platform', 'mode']

Import(CONFIG)

QUALIA_DIR = "../../"

if (platform == 'computer'):
  INCLUDE_PATH = "/Users/tats/Documents/workspace/qualia:/usr/local/include/qualia"
  LIBS="-lqualia"
else:
  INCLUDE_PATH = "/Users/tats/Documents/workspace/qualia:/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/avr/include/"

MCU = 'atmega168'
F_CPU = 16000000
EXTRA_LIBS = ""

if (platform == 'avr'):
  AVR_GCC_DIR = "/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/"

if (platform == 'arduino'):
  TARGET = 'MainTest'
else:
  TARGET = "unit_test"

Return(CONFIG)